### PR TITLE
Revert #240 - reverted bump of `laminas/laminas-coding-standard` to `^2.3.0`

### LINKED ISSUE #241: CI seems broken (2.14 is unusable)
Please check, for ex, https://github.com/laminas/laminas-db/runs/5743858834

It seems report for end of tests is missing, and thus probably missing some exit code
There is also a lot of failures / errors

```
PHPUnit 9.5.19 #StandWithUkraine

.............................SSSSSSSSSSSS...SS.....IIIII.IIII   61 / 1230 (  4%)
IIIIIIIIISSSSS...III..FFI.......SSSSSSSSSSSS.......SS.....III  122 / 1230 (  9%)
IIIIIIIIIIIIIII.......SSSS.......I.I.I......III..I...........  183 / 1230 ( 14%)
........................E...........RRRR...............S.....  244 / 1230 ( 19%)
..IIIII.......III..I....SIIIIIIIIIIIII........IIIII........II  305 / 1230 ( 24%)
IIII.........................................................  366 / 1230 ( 29%)
....................................R........................  427 / 1230 ( 34%)
.S.................................................R.......E.  488 / 1230 ( 39%)
.............................................................  549 / 1230 ( 44%)
..........S.........................................W.W......  610 / 1230 ( 49%)
.......................W........W........W........W..........  671 / 1230 ( 54%)
.............................................................  732 / 1230 ( 59%)
.........................................E...................  793 / 1230 ( 64%)
........................E...EE...............................  854 / 1230 ( 69%)
.............................RRRRRRRRR.RRRRRR.RRRR.RRRR..RRRR  915 / 1230 ( 74%)
RRRRRRRRRRRRR.R.RRRRR.R......................................  976 / 1230 ( 79%)
........................................................R.... 1037 / 1230 ( 84%)
.....R...RR.................................................. 1098 / 1230 ( 89%)
...................................W.....W................... 1159 / 1230 ( 94%)
........................................EE.FEEEEE..E.EEESEEEE 1220 / 1230 ( 99%)
.EE..EEarray(2) {
  [0]=>
  array(6) {
    [0]=>
    string(5) "42000"
    ["SQLSTATE"]=>
    string(5) "42000"
    [1]=>
    int(4060)
    ["code"]=>
    int(4060)
    [2]=>
    string(133) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "laminasdb_test" requested by the login. The login failed."
    ["message"]=>
    string(133) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "laminasdb_test" requested by the login. The login failed."
  }
  [1]=>
  array(6) {
    [0]=>
    string(5) "28000"
    ["SQLSTATE"]=>
    string(5) "28000"
    [1]=>
    int(18456)
    ["code"]=>
    int(18456)
    [2]=>
    string(81) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'sa'."
    ["message"]=>
    string(81) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'sa'."
  }
}
```

### PR DESCRIPTION
**Pull request by Ocramius**
Reverts laminas/laminas-db#240
Fixes #241 

/cc @ghostwriter @arueckauer

### CODE REVIEW

**Comment by Ocramius** [comment]
`7.3` + `latest` still fails, but better than a completely broken system:

```
FAILURES!
Tests: 1230, Assertions: 2077, Failures: 1, Warnings: 8, Skipped: 41, Incomplete: 80, Risky: 58.
```

**Comment by arueckauer** [comment]
Did not expect it to fail that bad. Thanks for both of your efforts!

**Comment by Ocramius** [comment]
@arueckauer heh, green CI on this was very unexpected anyway :D

**Comment by ghostwriter** [comment]
Why revert, instead of fixing the Types of the 2nd and 3rd arguments of `var_export` and `str_replace` respectively? 

When a “feature” is released, and caused an undesired outcome in production; how do you fix the issue?

**fix the issue in a minor patch**

Create a separate `bugfix` branch with the fix

**revert the feature**

What do you do here? 

Re-open the `feature` PR, fix the issue, re-merge?

Create a new `feature` Pr with code from feature branch with the additional bugfix commits?

I want to learn and understand the thought process behind the decisions so I can apply them correctly.

Thank you for you time.

**Comment by Ocramius** [comment]
The question is also timing: I didn't have time to investigate nor fix this, so a full revert was quick and viable.

Re-applying the patch is possible afterwards, in `2.15.x` or later, but for now, allowing usage of `2.14.1` takes priority.

**Comment by dstockto** [comment]
We ran into an issue w/ 2.14.0 as well - using non-strings (like ints) as literal column values mapped to a column name also caused a type error.

**Pull request merged**
