### PR TITLE
Drop support php 7, add php 8.2 support

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by fezfez** [comment]
@Ocramius php8.2-sqlsrv is apparently not ready

**Comment by Ocramius** [comment]
Will likely take another while too..

**Comment by fezfez** [comment]
Fixed by https://github.com/laminas/laminas-continuous-integration-action/pull/110 ?

**Comment by Ocramius** [comment]
Trying a re-run

**Comment by Ocramius** [comment]
Nope

**Comment by Ocramius** [comment]
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20220829/sqlsrv.so (/usr/lib/php/20220829/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20220829/sqlsrv.so.so (/usr/lib/php/20220829/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Fatal error:  Cannot alias 'Laminas\Db\Sql\Ddl\Column\Float' as it is a built-in type in /github/workspace/test/unit/Sql/Ddl/Column/FloatTest.php on line 5
```

**Comment by fezfez** [comment]
linked to https://github.com/microsoft/msphpsql/issues/1420

**Comment by fezfez** [comment]
@Ocramius seem good :nerd_face:

**Comment by Ocramius** [comment]
@fezfez could you clean up this git history a bit? Then good to go, IMO :)

**Comment by Ocramius** [comment]
Oh, never mind, you already did: thanks!

**Review by Ocramius — APPROVED** [review]
:ship:

**Pull request merged**
