### PR TITLE
Add support for PHP 8.0

### LINKED ISSUE #174: PHP 8.0 support
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

### PR DESCRIPTION
**Pull request by samsonasik**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description

Bumps php minimum requirement to 7.3 (alternative of #164) and provides support for PHP 8.0.

### CODE REVIEW

**Comment by samsonasik** [comment]
First, bump to php 7.3 with enable cs check and coverage at php 7.3 latest mysql env

**Comment by samsonasik** [comment]
Next, update components versions. For phpunit, it pinned to use `~9.1.5` as phpunit 9.2.0 cause error: 

```bash
1) LaminasTest\Db\Adapter\AdapterTest::testQueryWhenPreparedWithParameterArrayProducesResult
Non unique mocked method invocation: Laminas\Db\Adapter\Driver\DriverInterface::createStatement

/Users/samsonasik/www/laminas-contribute/laminas-db/src/Adapter/Adapter.php:191
/Users/samsonasik/www/laminas-contribute/laminas-db/test/unit/Adapter/AdapterTest.php:245

2) LaminasTest\Db\Adapter\AdapterTest::testQueryWhenPreparedWithParameterContainerProducesResult
Non unique mocked method invocation: Laminas\Db\Adapter\Driver\DriverInterface::createStatement

/Users/samsonasik/www/laminas-contribute/laminas-db/src/Adapter/Adapter.php:191
/Users/samsonasik/www/laminas-contribute/laminas-db/test/unit/Adapter/AdapterTest.php:263
```

like I commented at https://github.com/laminas/laminas-db/pull/164#issuecomment-639759364

**Comment by samsonasik** [comment]
Now, migrating phpunit syntax with @michalbundyra's https://github.com/webimpress/phpunit-migration ? Seems not all catched, some needs manually...

**Comment by michalbundyra** [comment]
@samsonasik 

> migrating phpunit syntax with @michalbundyra's https://github.com/webimpress/phpunit-migration ? Seems not all catched, some needs manually...

Not all is possible to be done automatically. This is just dev tool which should help with the main "migration", but some have to be done manually, that's right.

**Comment by samsonasik** [comment]
@michalbundyra yes, and it seems I was missed @weierophinney points at https://github.com/laminas/laminas-db/pull/164#pullrequestreview-431870439 , I think update phpunit syntax needs to be in separate PR after bumping php to 7.3 merged.

**Comment by samsonasik** [comment]
@weierophinney I shrinked the PR with only update php version in composer.json, travis, and remove the float class. It should be merge-able now.

Of course, travis will be failure at this point.

**Comment by samsonasik** [comment]
merge-able?

**Comment by michalbundyra** [comment]
@samsonasik first we need release bugfix version, before we start merging changes for next minor.

**Comment by samsonasik** [comment]
@michalbundyra bug fix version with remove `Float` class ? Is changing target to master is enough?

**Comment by michalbundyra** [comment]
@samsonasik no, sorry, I mean first we need to handle bugfix version (other PRs) before we can start merging features/removals for next minor.

**Comment by samsonasik** [comment]
ok :+1:

**Comment by samsonasik** [comment]
should php 8 added as well ?

**Comment by samsonasik** [comment]
I've added  php 8  as well.

**Comment by samsonasik** [comment]
I've updated php 8 version to use ~8.0.0

**Comment by fezfez** [comment]
any news on this ?

**Comment by samsonasik** [comment]
@fezfez while wait for it, you can temporary use my fork, you can set the following in your composer.json: 

```javascript
"require": {
     // ...
     "laminas/laminas-db": "dev-allow-php80-fork as 2.11.3",
     // ...
},

"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/samsonasik/laminas-db",
            "no-api": true
        }
]
```

My fork include the patch in the closed PR https://github.com/laminas/laminas-db/pull/164 as well which was too big to review.

**Comment by weierophinney** [comment]
@samsonasik I've rebased against 2.12.x, updated the phpunit minimum to 9.3, and updated the test suite so that tests run... but there are a number of errors being reported at this point.

If you want to pick it up, feel free - otherwise, I'll continue on Monday.

**Comment by samsonasik** [comment]
@weierophinney as I commented at https://github.com/laminas/laminas-db/pull/164#issuecomment-639759364 we can pin phpunit to ~9.1.5 for it to work first.

**Comment by weierophinney** [comment]
@samsonasik Interestingly, unit tests pass for me on PHP 7.4 locally; it's the integration tests that raise errors. I didn't have time to check what the errors were on php 8 before my laptop ran out of battery, though.

**Comment by weierophinney** [comment]
@samsonasik All the remaining issues were with usage of deprecated assertions, and the fact that PHP 8 is more strict with regards to types for arguments to internal functions and methods. I was able to get them all resolved relatively quickly today, while keeping the PHPUnit 9.3 requirement!

**Comment by samsonasik** [comment]
@weierophinney Thank you, the `Float` class not to be removed?

**Comment by samsonasik** [comment]
`Float` seems reserved keyword since php 7.2 https://3v4l.org/iS8qU

**Comment by weierophinney** [comment]
The unit tests didn't flag the Float class as an issue on PHP 8, so I'm leaving it for now.

**Comment by samsonasik** [comment]
@weierophinney that because excluded in phpunit.xml, I created new PR for it https://github.com/laminas/laminas-db/pull/184

**Pull request merged**
