### PR TITLE
Adding documentation on usage of laminas db in mvc application

### PR DESCRIPTION
**Pull request by haclong**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Documentation on one possible usage of the package with a Laminas MVC application.
Since this can have some impact on the configuration of docker containers, a new Dockerfile & docker-compose.yml are included in the documentation

### CODE REVIEW

**Comment by froschdesign** [comment]
@haclong 
> Documentation on one possible usage of the package with a Laminas MVC application.

The description contains _one possible usage_ but is this a typical usage to use different databases and different DBMS?
I see one more problem because the description only describes the part of the configuration but not the further usage of the adapter in a MVC application.

I would therefore suggest an example with a [repository](https://docs.laminas.dev/tutorials/in-depth-guide/laminas-db-sql-laminas-hydrator/#writing-the-repository-implementation) like we have in the tutorials.

Please also compare with the following descriptions:

* [laminas-form](https://docs.laminas.dev/laminas-form/application-integration/usage-in-a-laminas-mvc-application/)
* [laminas-inputfilter](https://docs.laminas.dev/laminas-inputfilter/application-integration/usage-in-a-laminas-mvc-application/)

> Since this can have some impact on the configuration of docker containers, a new Dockerfile & docker-compose.yml are included in the documentation.

If we add the documentation for Docker at this place, we need to repeat it in other component documentation as well. For example in the documentation of laminas-mvc. We should separate the usage with Docker in a tutorial and add a link to all needed components.

**Comment by haclong** [comment]
@froschdesign 
no pb.
i'm just confused because last time i contributed, the PR was denied because the documentation i proposed was for some part already included  in the tutorial

plus, based on the other components documentation, they refer to the tutorial application which already include what i think is a basic implementation of the repository.

so i focused more on bits that took me time to google for in the past.

i'll change the PR but i'm just worry : 
if i include an example with a repository like we have in the tutorials, as you said, it is already in the tutorial. Wouldn't it be a duplicate now ? or does it mean we are going to remove the part in the tutorial ? 
if i decide to give a further example of the repository, so wouldn't it be too close to the TableGateway documentation page ?

the boundaries are very thin but i'll do my best.

as for the Docker part, i agree,
i think it is best to have documentation on integration with other tools (infrastructure or librairies) in separated part of the documentation. 

as for the tone, do you think it is good enough ? i use to write in a more personal tone but i know you prefer the documentation to be more formal...

**Comment by froschdesign** [comment]
@haclong 
> if i include an example with a repository like we have in the tutorials, as you said, it is already in the tutorial. Wouldn't it be a duplicate now ? or does it mean we are going to remove the part in the tutorial ?

The description for application integration must contain a basic but working example. An example with a lot of features is for the tutorials.
This means for this component only one method of the repository should be filled with code, like we have only [one input](https://docs.laminas.dev/laminas-inputfilter/application-integration/usage-in-a-laminas-mvc-application/#create-input-filter) or [one element](https://docs.laminas.dev/laminas-form/application-integration/usage-in-a-laminas-mvc-application/#create-form) in the descriptions for laminas-inputfilter and laminas-form.

> if i decide to give a further example of the repository, so wouldn't it be too close to the TableGateway documentation page ?

That would even be right because _in the best case_ the description for application integration is only a coherent example of individual descriptions of the component documentation.

See also the cards with notes in the related project: https://github.com/orgs/laminas/projects/3

> i think it is best to have documentation on integration with other tools (infrastructure or librairies) in separated part of the documentation.

Right!

---

Later there should also be an overview of the available descriptions for application integrations under the tutorials. (The idea is there, but still needs to be worked out.)

**Comment by froschdesign** [comment]
@weierophinney 
I made a big mistake here because I forgot to mark this pull request as draft / "work in progress".

The description is missing everything what is required to show how laminas-db can be used inside a mvc-based application. No repository or table gateway, no controller, no factory, no module configuration, etc.
Unfortunately, everything that should be available for the user under this heading is missing.

Related issue report for this topic: https://github.com/laminas/documentation/issues/8

I'm sorry but we have to revert this.

**Pull request merged**
