### PR TITLE
Added MS SQL server that can be used to better test the integration.

### PR DESCRIPTION
**Pull request by slaff**
This PR is the first one from a series of PRs to add metadata support for IBM DB2.

### CODE REVIEW

**Comment by slaff** [comment]
@weierophinney Thank you Matthew! I was struggling with the transition from travis to GHA.

**Comment by weierophinney** [comment]
@slaff My pleasure - thanks for getting this started! You did the majority of the work; the main things I had to update:

- The healthcheck command - for some reason, the sqlcmd binary is not on the path in the container, so you need to specify the full path to it. Once I did that, health checks succeeded, and we could move on to testing.
- I needed to add support for the sqlsrv extensions to our CI container.
- I had to add configuration to enable the sqlsrv extensions during our CI runs.

Once those were in place, it was just a matter of fixing some assertions!

**Comment by slaff** [comment]
@weierophinney What is the recommended way to continue adding new PRs? Shall I create PR against the default branch, which is  currently `2.13.x`, or there will be a `develop` branch?

**Comment by weierophinney** [comment]
Do them against the current default release branch (2.13.x).

That said... we're preparing to mark this component security only, per a [decision by the TSC last summer](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).

**Pull request merged**
